app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime


class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255), unique = True, index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_hash = db.Column(db.String(255))
    pitcher = db.relationship("Pitch", backref= "user", lazy="dynamic")
    reviews = db.relationship("Review", backref = "user", lazy = "dynamic")

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    
    def hash_password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f'User {self.username}'
    

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))
    

class PhotoProfile(db.Model):
    __tablename__ = 'profile_photos'

    id = db.Column(db.Integer,primary_key = True)
    pic_path = db.Column(db.String())
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectField, SubmitField
from wtforms.validators import Required



# class PitchForm(FlaskForm):
#     category = SelectField('Category', choices=[('', ''), ('pickup lines', 'Pickup Lines'), ('technology', 'Technology Pitches'), ('product', 'Product Pitches'), ('family', 'Family Pitches'), ('jokes', 'Jokes Pitches'), ('motivational', 'Motivational Pitches'), ('educational', 'Educational Pitches')], validators = [Required()])
#     title = StringField('Pitch title', validators = [Required()])
#     pitch = TextAreaField('Pitch', validators = [Required()])
#     submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_uploads import UploadSet, configure_uploads, IMAGES
from config import config_options
from flask_mail import Mail
from flask_simplemde import SimpleMDE

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()

photos = UploadSet('photos', IMAGES)

mail = Mail()
simple = SimpleMDE()

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Intializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)


    # Will add the views and forms

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # configure UploadSet
    configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint( 'main', __name__ )
from . import views,forms

app/main/views.py
from flask import render_template, request, redirect, url_for, abort
from . import main
# from .forms import [form_name]
from ..models import User
from .. import db, photos
from flask_login import login_required, current_user
import markdown2

@main.route('/')
def index():
    '''
    View root page function that returns the index page 
    '''
    
    return render_template( 'index.html', title = title )

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)
    return render_template("profile/profile.html", user = user)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)
    form = UpdateProfile()
    if form.validate_on_submit():
        user.bio = form.bio.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('.profile', uname = user.username ))
    return render_template('profile/update.html', form = form, user = user )

app/templates/base.html
{% extends 'bootstrap/base.html' %}
<!-- Navbar block  --> 

{% block navbar %}
<header>
  {% include 'navbar.html' %}
</header>

{% endblock %}



{%block styles %}
  {{super()}}
  <!--Importing the simple mde css and js files  -->
  {{ simplemde.css}}
  {{ simplemde.js }}

{% endblock %}
{% block content %}
{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html' %}

{% block content %}
    <h1>WHOOPS we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}
<link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Josefin+Sans|Roboto+Mono|Shadows+Into+Light&display=swap" rel="stylesheet">

<!-- Styles block -->
<body>


{% block styles%}
    {{ super() }}
   
{% endblock %}

{% block content %}
{% if current_user.is_authenticated %}
<a href="/user/{{current_user.username}}/pitch" class="btn btn-success">+ pitch</a>

{% endif %}
<div class="main " style="background-image:url(https://images.unsplash.com/photo-1556634862-107d22db86eb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60)" >
    <div class="container">
        <h1 style="text-align: center" class="title">Pitcher</h1>
        <div class="card" style="width: 18rem;">
            <div class="card-header">
                Requirements to post a pitch
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><h4>Sign up and login to access content</h4></li>
                <li class="list-group-item"><h4>Receive a welcoming email once you sign up</h4></li>
                <li class="list-group-item"><h4>Post a pitch for you or for someone to comment</h4></li>
                <li class="list-group-item"><h4>Comment on a pitch</h4></li>
                <li class="list-group-item"><h4>Vote a pitch </h4></li>

            </ul>
        </div>
    </div>
</div>
<hr>
<br>
<br>
{% endblock %}   
</body>

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand">Pitcher</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li> <a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a> </li>
                <li style="color:white;padding:15px;">{{current_user.username}}</li>
                <li><a href="{{url_for('auth.logout')}}">Sign Out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}

<div class="container">

<div class="row">


  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    {% if user.bio %}
      <p> {{user.bio}}</p>

    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}

    {% if user == current_user %}
      <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
    {% endif %}

  </div>
  <div class="col-md-4">
    {% if user.profile_pic_path %}

    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

    {%else%}
    <p>No profile picture</p>
    {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}
 

    {% endif %}
  </div>


</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}